### ISSUE TITLE
'Exclude' syntax

### ISSUE THREAD

**Issue by madeInLagny** [LarsDenBakker/rollup-plugin-dynamic-import-variables#5]
Thanks for this great plugin. One of my dynamic imports refers to a folder that has the following structure views/[view-name]/[viewn-name].js. Example: views/home-page/home-page.js
I want to exclude views/template-page/template-page.js from your plugin. I tried several syntaxes, including a straight:
```
dynamicImportVariables({
      exclude: 'template-page.js',
    }),
```
but it does not work. Any ideas ?

**Comment by LarsDenBakker** [comment]
This follows the same pattern as other rollup plugins: https://github.com/rollup/plugins/tree/master/packages/pluginutils#createfilter

In your case it would need to be `views/home-page/home-page.js`, if your current working directory is the folder above the `views` folder. Or something like `**/*/home-page.js`. 

Note that this plugin has become an official rollup plugin: https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars it's best to use it from there

**Comment by madeInLagny** [comment]
Thanks Lars for your continuous great support.
